# Generated by Django 3.0.7 on 2020-11-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='location',
        ),
    ]
